# Generated by Django 5.1.1 on 2024-10-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=255)),
                ('cover', models.ImageField(upload_to='images/')),
                ('readersTotal', models.PositiveIntegerField(default=0)),
                ('readersWeek', models.PositiveIntegerField(default=0)),
                ('releaseDate', models.DateTimeField()),
                ('numberPages', models.PositiveIntegerField()),
                ('rating', models.FloatField(default=0)),
            ],
        ),
    ]
