# Generated by Django 5.1.1 on 2024-10-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_cover_bookedition_cover_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedition',
            old_name='number_pages',
            new_name='numberPages',
        ),
    ]
